version: 2.1
jobs:
  build:
    working_directory: ~/rust-playground
    docker:
      - image: rust:1.70.0
    steps:
      - checkout
      - run: rustc HelloWorld.rs
      - run: rustc HelloWorld2.rs
      - run: rustc HelloWorld3.rs
      - run: ./HelloWorld
      - run: ./HelloWorld2
      - run: ./HelloWorld3
      - run: |
          cd hello
          cargo run
          cargo build --release
          cargo run --release

workflows:
  version: 2
  build:
    jobs:
      - build
  daily_workflow:
    triggers:
      - schedule:
          cron: "0 20 * * *"
          filters:
            branches:
              only: /master/
    jobs:
      - build
